apiVersion: v1
kind: Template
metadata:
  name: grafana
  annotations:
    openshift.io/display-name: Grafana
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: grafana
    name: grafana
    namespace: new-project-monitoring
  spec:
    replicas: 1
    selector:
      app: grafana
      deploymentconfig: grafana
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: grafana
          deploymentconfig: grafana
      spec:
        containers:
        - image: docker-registry.default.svc:5000/openshift/grafana:6.5.2
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboards
            - mountPath: /etc/grafana
              name: grafana-config
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
        volumes:
          - configMap:
              defaultMode: 420
              name: grafana-dashboards
            name: grafana-dashboards
          - configMap:
              defaultMode: 420
              name: grafana-config
            name: grafana-config
          - name: grafana-datasources
            secret:
              defaultMode: 420
              secretName: grafana-datasource
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
      deploymentconfig: grafana
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    to:
      kind: Service
      name: grafana