apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource
  namespace: new-project-monitoring
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      access: proxy
      url: http://prometheus.new-project-monitoring.svc.cluster.local:9090
      basicAuth: false
      withCredentials: false
      isDefault: true
      jsonData:
        tlsSkipVerify: true
      editable: false