apiVersion: v1
kind: Secret
metadata:
  name: openshift-monitoring-grafana-datasource
  namespace: openshift-monitoring
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      access: proxy
      url: https://prometheus.openshift-metrics.svc:9091
      basicAuth: true
      basicAuthPassword: cMY/qdTjLzD6FNBuIXoHSakDUaINtH9/yekX17s1da0Z/harjOSrQXWEN/+wePBguWfLxnG2QlerKtJOsfk48ccF9BKug4z0405Z97fNnlNy0FZ/9IwlyKzxvSjIX9OVtwCfaR+KMB2oxAVHKCK8ZKELPix/UfBBEeYs04TaxkZDWgaSD2N24IeI9yW/4HQgpqXQTrZTTUUnMe+6HJ9QlYhVtvwmlQUdPejy8jmfRe+0WxCYxnJBH6Eo4cpFnAuO9LzeJcfYvUPLW5/kKKsDsrSzwHuiweM7FviYDud3TlDtAw1t3V7lDcAUz7xjfDaIxQSV+dmNwKqBjAx0BDLW
      basicAuthUser: internal
      withCredentials: false
      isDefault: true
      jsonData:
        tlsSkipVerify: true
      editable: false